# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import swapi_pb2 as swapi__pb2


class SwapiServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPerson = channel.unary_unary(
                '/swapi.SwapiService/GetPerson',
                request_serializer=swapi__pb2.GetPersonRequest.SerializeToString,
                response_deserializer=swapi__pb2.Person.FromString,
                )


class SwapiServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPerson(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SwapiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPerson': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPerson,
                    request_deserializer=swapi__pb2.GetPersonRequest.FromString,
                    response_serializer=swapi__pb2.Person.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swapi.SwapiService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SwapiService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPerson(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swapi.SwapiService/GetPerson',
            swapi__pb2.GetPersonRequest.SerializeToString,
            swapi__pb2.Person.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
