# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: swapi.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bswapi.proto\x12\x05swapi\"\x1e\n\x10GetPersonRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"U\n\x06Person\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\nbirth_year\x18\x03 \x01(\t\x12\x0e\n\x06gender\x18\x04 \x01(\t\x12\r\n\x05\x66ilms\x18\x05 \x03(\t2E\n\x0cSwapiService\x12\x35\n\tGetPerson\x12\x17.swapi.GetPersonRequest\x1a\r.swapi.Person\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'swapi_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETPERSONREQUEST._serialized_start=22
  _GETPERSONREQUEST._serialized_end=52
  _PERSON._serialized_start=54
  _PERSON._serialized_end=139
  _SWAPISERVICE._serialized_start=141
  _SWAPISERVICE._serialized_end=210
# @@protoc_insertion_point(module_scope)
