# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: swapi.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bswapi.proto\x12\x05swapi\"\x1e\n\x10GetPersonRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x1f\n\x11GetSpeciesRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x1e\n\x10GetPlanetRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"F\n\x06Person\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\nbirth_year\x18\x03 \x01(\t\x12\x0e\n\x06gender\x18\x04 \x01(\t\"g\n\x07Species\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x16\n\x0e\x63lassification\x18\x03 \x01(\t\x12\x18\n\x10\x61verage_lifespan\x18\x04 \x01(\t\x12\x10\n\x08language\x18\x05 \x01(\t\"E\n\x06Planet\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08\x64iameter\x18\x03 \x01(\t\x12\x0f\n\x07\x63limate\x18\x04 \x01(\t2\xb6\x01\n\x0cSwapiService\x12\x35\n\tGetPerson\x12\x17.swapi.GetPersonRequest\x1a\r.swapi.Person\"\x00\x12\x38\n\nGetSpecies\x12\x18.swapi.GetSpeciesRequest\x1a\x0e.swapi.Species\"\x00\x12\x35\n\tGetPlanet\x12\x17.swapi.GetPlanetRequest\x1a\r.swapi.Planet\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'swapi_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETPERSONREQUEST._serialized_start=22
  _GETPERSONREQUEST._serialized_end=52
  _GETSPECIESREQUEST._serialized_start=54
  _GETSPECIESREQUEST._serialized_end=85
  _GETPLANETREQUEST._serialized_start=87
  _GETPLANETREQUEST._serialized_end=117
  _PERSON._serialized_start=119
  _PERSON._serialized_end=189
  _SPECIES._serialized_start=191
  _SPECIES._serialized_end=294
  _PLANET._serialized_start=296
  _PLANET._serialized_end=365
  _SWAPISERVICE._serialized_start=368
  _SWAPISERVICE._serialized_end=550
# @@protoc_insertion_point(module_scope)
